package export

import (
	"fmt"
	"strings"

	"github.com/org/experimentation-platform/services/metrics/internal/querylog"
)

const (
	databricksHeader    = "# Databricks notebook source"
	databricksDelimiter = "# COMMAND ----------"
	databricksMagicMD   = "# MAGIC %md"
)

// GenerateDatabricksNotebook creates a Databricks-compatible Python notebook
// (.py format with # MAGIC and # COMMAND markers) from query log entries.
// This can be imported directly into a Databricks workspace.
func GenerateDatabricksNotebook(experimentID string, entries []querylog.Entry) ([]byte, error) {
	var b strings.Builder

	// Databricks source header.
	b.WriteString(databricksHeader)
	b.WriteString("\n\n")

	// Title markdown cell.
	b.WriteString(databricksMagicMD)
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("# MAGIC # Experiment Analysis: %s\n", experimentID))
	b.WriteString("# MAGIC\n")
	b.WriteString("# MAGIC This notebook was auto-generated by the Experimentation Platform.\n")
	b.WriteString("# MAGIC It contains all SQL queries executed during metric computation.\n")
	b.WriteString("\n")
	b.WriteString(databricksDelimiter)
	b.WriteString("\n\n")

	// Setup cell: create SparkSession reference.
	b.WriteString("# SparkSession is pre-configured in Databricks — `spark` is available by default.\n")
	b.WriteString("# If running locally, uncomment the following:\n")
	b.WriteString("# from pyspark.sql import SparkSession\n")
	b.WriteString("# spark = SparkSession.builder.appName('experiment-analysis').getOrCreate()\n")

	// One markdown + code cell per query entry.
	for _, entry := range entries {
		b.WriteString("\n")
		b.WriteString(databricksDelimiter)
		b.WriteString("\n\n")

		// Markdown description cell.
		b.WriteString(databricksMagicMD)
		b.WriteString("\n")
		b.WriteString(fmt.Sprintf("# MAGIC ## Metric: %s\n", entry.MetricID))
		b.WriteString("# MAGIC\n")
		b.WriteString(fmt.Sprintf("# MAGIC - **Job type**: %s\n", entry.JobType))
		b.WriteString(fmt.Sprintf("# MAGIC - **Row count**: %d\n", entry.RowCount))
		b.WriteString(fmt.Sprintf("# MAGIC - **Duration**: %d ms\n", entry.DurationMs))
		b.WriteString("\n")
		b.WriteString(databricksDelimiter)
		b.WriteString("\n\n")

		// Code cell with the SQL query.
		b.WriteString(fmt.Sprintf("df = spark.sql('''\n%s\n''')\n", entry.SQLText))
		b.WriteString("\n")
		b.WriteString("display(df)\n")
		b.WriteString("df.describe().show()\n")
	}

	return []byte(b.String()), nil
}
