// Package export generates Jupyter notebooks from query log entries.
package export

import (
	"encoding/json"
	"fmt"

	"github.com/org/experimentation-platform/services/metrics/internal/querylog"
)

// Cell represents a single Jupyter notebook cell.
type Cell struct {
	CellType string   `json:"cell_type"`
	Source   []string `json:"source"`
	Metadata map[string]any `json:"metadata"`
	Outputs  []any  `json:"outputs"`
}

// Notebook represents a Jupyter .ipynb file.
type Notebook struct {
	NBFormat      int    `json:"nbformat"`
	NBFormatMinor int    `json:"nbformat_minor"`
	Metadata      NotebookMetadata `json:"metadata"`
	Cells         []Cell `json:"cells"`
}

// NotebookMetadata holds notebook-level metadata.
type NotebookMetadata struct {
	KernelSpec KernelSpec `json:"kernelspec"`
	LanguageInfo LanguageInfo `json:"language_info"`
}

// KernelSpec identifies the notebook kernel.
type KernelSpec struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Language    string `json:"language"`
}

// LanguageInfo describes the notebook's language.
type LanguageInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// GenerateNotebook creates a valid .ipynb JSON from query log entries.
func GenerateNotebook(experimentID string, entries []querylog.Entry) ([]byte, error) {
	nb := Notebook{
		NBFormat:      4,
		NBFormatMinor: 5,
		Metadata: NotebookMetadata{
			KernelSpec: KernelSpec{
				Name:        "python3",
				DisplayName: "Python 3",
				Language:    "python",
			},
			LanguageInfo: LanguageInfo{
				Name:    "python",
				Version: "3.10.0",
			},
		},
		Cells: make([]Cell, 0, 2+len(entries)*2),
	}

	// Header cell.
	nb.Cells = append(nb.Cells, Cell{
		CellType: "markdown",
		Source: []string{
			fmt.Sprintf("# Experiment Analysis: %s\n", experimentID),
			"\n",
			"This notebook was auto-generated by the Experimentation Platform.\n",
			"It contains all SQL queries executed during metric computation.\n",
		},
		Metadata: map[string]any{},
	})

	// Setup cell.
	nb.Cells = append(nb.Cells, Cell{
		CellType: "code",
		Source: []string{
			"from pyspark.sql import SparkSession\n",
			"\n",
			"spark = SparkSession.builder \\\n",
			"    .appName('experiment-analysis') \\\n",
			"    .getOrCreate()\n",
		},
		Metadata: map[string]any{},
		Outputs:  []any{},
	})

	// One markdown + code cell pair per query.
	for _, entry := range entries {
		// Markdown description.
		nb.Cells = append(nb.Cells, Cell{
			CellType: "markdown",
			Source: []string{
				fmt.Sprintf("## Metric: %s\n", entry.MetricID),
				"\n",
				fmt.Sprintf("- **Job type**: %s\n", entry.JobType),
				fmt.Sprintf("- **Row count**: %d\n", entry.RowCount),
				fmt.Sprintf("- **Duration**: %d ms\n", entry.DurationMs),
			},
			Metadata: map[string]any{},
		})

		// Code cell with the SQL (using triple-quoted string for safety).
		nb.Cells = append(nb.Cells, Cell{
			CellType: "code",
			Source: []string{
				fmt.Sprintf("df = spark.sql('''\n%s\n''')\n", entry.SQLText),
				"\n",
				"df.show(20)\n",
				"df.describe().show()\n",
			},
			Metadata: map[string]any{},
			Outputs:  []any{},
		})
	}

	data, err := json.MarshalIndent(nb, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("export: marshal notebook: %w", err)
	}
	return data, nil
}
