#!/usr/bin/env python3
"""Generate sibling-repo governance onboarding files from the fleet config (H6).

Reads the single source of truth — infra/github-governance/Pulumi.governance.yaml
— and emits, for every fleet repo EXCEPT this one (whose callers are the
local-path variants already in .github/workflows/):

  <out>/<repo>/.github/workflows/review-gate.yml   ── thin callers of this
  <out>/<repo>/.github/workflows/pr-title.yml         repo's reusable
  <out>/<repo>/.github/workflows/automerge.yml        _*.yml workflows
  <out>/<repo>/.github/rulesets/main.json          ── that repo's branch
                                                      ruleset (governance +
                                                      repo CI contexts,
                                                      enforcement from config)
  <out>/<repo>/README.md                           ── apply instructions

Modes
  --out DIR       output tree (default: dist/governance-onboarding)
  --apply PARENT  additionally copy workflows + ruleset into PARENT/<repo>/
                  for every sibling checkout that exists there (the ecosystem
                  layout keeps all repos side by side). Never deletes; reports
                  created/updated/unchanged per file. README is not copied —
                  its content is printed as next steps instead.

Every emitted workflow is re-parsed as YAML and every `uses:` target is
checked to exist in this repo, so a rename of a reusable workflow breaks this
generator loudly instead of producing callers that point at nothing.

Runbook: docs/runbooks/ecosystem-governance.md.  Justfile: `just
governance-onboard` / `just governance-onboard-apply`.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
FLEET_CONFIG = REPO_ROOT / "infra" / "github-governance" / "Pulumi.governance.yaml"
HOST_REPO = "kaizen-experimentation"  # its callers are the local-path ones
REUSABLES = ["_review-gate.yml", "_pr-title.yml", "_automerge.yml", "_pr-size.yml"]

try:
    import yaml
except ImportError:  # pragma: no cover
    print(
        "error: PyYAML is required (python3 -m pip install pyyaml) — the fleet "
        "config is nested YAML and a regex fallback would be too brittle here.",
        file=sys.stderr,
    )
    sys.exit(2)


def load_spec() -> dict:
    data = yaml.safe_load(FLEET_CONFIG.read_text())
    try:
        return data["config"]["kaizen-github-governance:spec"]
    except (KeyError, TypeError):
        print(f"error: kaizen-github-governance:spec not found in {FLEET_CONFIG}", file=sys.stderr)
        sys.exit(2)


def workflows_ref(spec: dict) -> str:
    """owner/repo@ref hosting the reusable workflows.

    Derived from the fleet entry for THIS repo so an org transfer (owner edit
    in the fleet config) re-points every generated caller on the next run.
    Override with GOVERNANCE_WORKFLOWS_REF=owner/repo@ref.
    """
    env = os.environ.get("GOVERNANCE_WORKFLOWS_REF")
    if env:
        return env
    for r in spec.get("repos", []):
        if r.get("name") == HOST_REPO:
            return f"{r['owner']}/{HOST_REPO}@main"
    return f"wunderkennd/{HOST_REPO}@main"


GENERATED_BANNER = """\
# GENERATED by scripts/generate_governance_onboarding.py (kaizen-experimentation)
# from infra/github-governance/Pulumi.governance.yaml — regenerate rather than
# hand-edit; see docs/runbooks/ecosystem-governance.md.
"""


def review_gate_caller(ref_repo: str, ref: str) -> str:
    return f"""{GENERATED_BANNER}name: Review gate

# PR-lifecycle gate: blocks merge while reviewer feedback is unaddressed.
# Logic lives in the reusable workflow — this caller owns triggers and the
# per-PR concurrency group. Check context: "Review gate / gate".
# NOTE: pull_request_review_thread is NOT a usable trigger on this GitHub
# (validator rejects it); the reusable's grace window covers resolve clicks.

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
  pull_request_review:
    types: [submitted, edited, dismissed]
  pull_request_review_comment:
    types: [created, edited, deleted]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: review-gate-${{{{ github.event.pull_request.number }}}}
  cancel-in-progress: true

jobs:
  gate:
    name: Review gate
    if: '!github.event.pull_request.draft'
    permissions:
      contents: read
      pull-requests: read
    uses: {ref_repo}/.github/workflows/_review-gate.yml@{ref}
"""


def pr_title_caller(ref_repo: str, ref: str) -> str:
    return f"""{GENERATED_BANNER}name: PR title check

# Conventional-Commit PR title lint. Check context: "PR title check / check".

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

permissions:
  contents: read

jobs:
  check:
    name: PR title check
    uses: {ref_repo}/.github/workflows/_pr-title.yml@{ref}
"""


def automerge_caller(ref_repo: str, ref: str) -> str:
    return f"""{GENERATED_BANNER}name: Auto-merge routine PRs

# Graduated review: arms squash auto-merge on ready, non-risk PRs; the
# platform merges once required checks (incl. the Review gate) are green.
# Tune the inputs to this repo's risk model.

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize, labeled, unlabeled]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: automerge-${{{{ github.event.pull_request.number }}}}
  cancel-in-progress: true

jobs:
  automerge:
    name: auto-merge
    if: '!github.event.pull_request.draft'
    permissions:
      contents: write
      pull-requests: write
    uses: {ref_repo}/.github/workflows/_automerge.yml@{ref}
    with:
      risk-labels: "breaking,needs-human-input"
      # Comma-separated path prefixes that force human review, e.g. "proto/,migrations/".
      risky-path-prefixes: ""
"""


def pr_size_caller(ref_repo: str, ref: str) -> str:
    return f"""{GENERATED_BANNER}name: PR size

# Right-sized-PR gate (origin: kaizen-experimentation #684 — omnibus PRs
# review worse). Soft limit warns, hard limit fails; 'oversize-approved'
# label + justifying comment overrides for genuinely atomic diffs.
# Context: "PR size / check". Thresholds/exemptions tunable via `with:`.

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: pr-size-${{{{ github.event.pull_request.number }}}}
  cancel-in-progress: true

jobs:
  check:
    name: PR size
    permissions:
      contents: read
      pull-requests: read
    uses: {ref_repo}/.github/workflows/_pr-size.yml@{ref}
"""


def ruleset_json(repo: dict, spec: dict) -> str:
    contexts, seen = [], set()
    for c in list(spec.get("governanceChecks", [])) + list(repo.get("requiredChecks", []) or []):
        if c and c not in seen:
            seen.add(c)
            contexts.append(c)
    ruleset = {
        "//": [
            f"GENERATED for {repo['owner']}/{repo['name']} by",
            "scripts/generate_governance_onboarding.py (kaizen-experimentation)",
            "from infra/github-governance/Pulumi.governance.yaml.",
            "One-off apply:",
            f"  gh api repos/{repo['owner']}/{repo['name']}/rulesets -X POST --input .github/rulesets/main.json",
            "(needs Administration: write). Prefer the Pulumi stack for the fleet:",
            "infra/github-governance/ — this file and that config encode the same intent.",
            "Enforcement starts as configured in the fleet list; flip to 'active'",
            "only after the caller workflows report on a live PR (a required",
            "check that never reports blocks every merge).",
        ],
        "name": "main",
        "target": "branch",
        "enforcement": repo.get("enforcement") or "disabled",
        "conditions": {"ref_name": {"include": ["~DEFAULT_BRANCH"], "exclude": []}},
        "rules": [
            {"type": "deletion"},
            {"type": "non_fast_forward"},
            {"type": "required_linear_history"},
            {
                "type": "pull_request",
                "parameters": {
                    "required_approving_review_count": 0,
                    "required_review_thread_resolution": True,
                    "dismiss_stale_reviews_on_push": False,
                    "require_code_owner_review": False,
                    "require_last_push_approval": False,
                },
            },
            {
                "type": "required_status_checks",
                "parameters": {
                    "strict_required_status_checks_policy": False,
                    "required_status_checks": [{"context": c} for c in contexts],
                },
            },
        ],
        "bypass_actors": [],
    }
    return json.dumps(ruleset, indent=2) + "\n"


def repo_readme(repo: dict, ref_repo: str, ref: str) -> str:
    full = f"{repo['owner']}/{repo['name']}"
    return f"""# Governance onboarding — {full}

Generated from `infra/github-governance/Pulumi.governance.yaml` (kaizen-experimentation).
Full narrative: `docs/runbooks/ecosystem-governance.md` there.

1. Copy `.github/` from this directory into a checkout of `{full}`
   (or run `just governance-onboard-apply` next to your sibling checkouts).
2. Open a PR in `{full}` with the four workflows; verify the checks report as
   `Review gate / gate`, `PR title check / check`, and `PR size / check` on
   that PR.
3. Apply the ruleset (choose one):
   - Fleet (preferred): set `enforcement: active` for `{repo['name']}` in the
     fleet config and `pulumi up` in `infra/github-governance/`.
   - One-off: `gh api repos/{full}/rulesets -X POST --input .github/rulesets/main.json`
     — after editing `"enforcement"` to `"active"`.
4. Repo toggles (Settings → General): Allow auto-merge ✓, Automatically delete
   head branches ✓.
5. Add this repo's own CI contexts to `requiredChecks` in the fleet config so
   the ruleset requires them too.

Callers reference `{ref_repo}@{ref}` — re-run the generator after any org
transfer so the refs re-point.
"""


def emit(spec: dict, out: Path) -> dict[str, dict[str, str]]:
    """Generate content for every sibling; write under out/; return
    {repo_name: {relpath: content}} for apply-mode reuse."""
    ref_repo, _, ref = workflows_ref(spec).partition("@")
    ref = ref or "main"
    generated: dict[str, dict[str, str]] = {}

    for reusable in REUSABLES:
        target = REPO_ROOT / ".github" / "workflows" / reusable
        if not target.exists():
            print(f"error: reusable workflow missing: {target} — generator out of date?", file=sys.stderr)
            sys.exit(1)

    for repo in spec.get("repos", []):
        name = repo.get("name")
        if not name or name == HOST_REPO:
            continue
        files = {
            ".github/workflows/review-gate.yml": review_gate_caller(ref_repo, ref),
            ".github/workflows/pr-title.yml": pr_title_caller(ref_repo, ref),
            ".github/workflows/automerge.yml": automerge_caller(ref_repo, ref),
            ".github/workflows/pr-size.yml": pr_size_caller(ref_repo, ref),
            ".github/rulesets/main.json": ruleset_json(repo, spec),
            "README.md": repo_readme(repo, ref_repo, ref),
        }
        # Self-validation: emitted YAML must parse; emitted JSON must load.
        for rel, content in files.items():
            if rel.endswith((".yml", ".yaml")):
                yaml.safe_load(content)
            elif rel.endswith(".json"):
                json.loads(content)
        for rel, content in files.items():
            dest = out / name / rel
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(content)
        generated[name] = files
        print(f"  generated {name}/ ({len(files)} files)")
    return generated


def apply_to_checkouts(generated: dict[str, dict[str, str]], parent: Path) -> int:
    """Copy workflows + ruleset (not README) into PARENT/<repo>/ checkouts."""
    missing = 0
    for name, files in sorted(generated.items()):
        checkout = parent / name
        if not checkout.is_dir():
            print(f"  skip {name}: no checkout at {checkout}")
            missing += 1
            continue
        for rel, content in files.items():
            if rel == "README.md":
                continue
            dest = checkout / rel
            if dest.exists() and dest.read_text() == content:
                state = "unchanged"
            else:
                state = "updated" if dest.exists() else "created"
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_text(content)
            print(f"  {state:9} {dest}")
        print(f"  → next: commit + PR in {name}, then follow README steps 2–5")
    return missing


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="dist/governance-onboarding", help="output directory (default: %(default)s)")
    ap.add_argument("--apply", metavar="PARENT", help="also copy into PARENT/<repo>/ sibling checkouts")
    args = ap.parse_args()

    spec = load_spec()
    out = Path(args.out)
    print(f"fleet config: {FLEET_CONFIG.relative_to(REPO_ROOT)}")
    print(f"reusable workflows ref: {workflows_ref(spec)}")
    generated = emit(spec, out)
    if not generated:
        print("error: no sibling repos in fleet config — nothing to generate", file=sys.stderr)
        return 1
    print(f"✓ {len(generated)} sibling repo(s) → {out}/")

    if args.apply:
        print(f"applying into checkouts under {args.apply}/ …")
        apply_to_checkouts(generated, Path(args.apply))
    return 0


if __name__ == "__main__":
    sys.exit(main())
