/**
 * MetricQL CodeMirror 6 language support (B2, ADR-026 Phase 2 #436).
 *
 * Wraps the Lezer parser generated by B1's build:grammar step into a full CM6
 * LanguageSupport object.  Import via `metricql()` and add to an EditorState's
 * extensions list.
 *
 * Tag mapping: Lezer node names (from metricql.grammar) are mapped to the
 * standard @lezer/highlight tag set so that defaultHighlightStyle renders them
 * correctly.  Mapping may be refined during B6 visual testing without API churn.
 */

import { LRLanguage, LanguageSupport, indentNodeProp } from '@codemirror/language';
import { styleTags, tags as t } from '@lezer/highlight';
import { parser } from './metricql';

// Grammar node names (from metricql.grammar):
//   Expression, AggFunc, Source, FieldRef, MetricRef, filter, predicate,
//   operator, value, window, timeUnit, ratio, composite, term, unary, factor
// Token names:
//   Identifier, Number, String
//   percentile, mean, sum, count, count_distinct, proportion  (AggFunc specializations)
//   where, and, in, within, of, exposure, hours, days         (keyword specializations)
//   ratio                                                      (keyword specialization)
//   Punctuation: ( ) [ ] , . @ + - * / = != < <= > >=

const metricqlLanguage = LRLanguage.define({
  name: 'metricql',
  parser: parser.configure({
    props: [
      styleTags({
        // Aggregate function keywords → function(variableName) tag.
        // Space-separated keys in styleTags map multiple node names to one tag.
        'mean sum count count_distinct proportion percentile ratio': t.function(t.variableName),

        // Control keywords (where clause and window clause).
        'where and in within of exposure hours days': t.controlKeyword,

        // Terminals.
        Number: t.number,
        String: t.string,

        // @metric_ref — highlight the whole MetricRef node as a variable.
        MetricRef: t.variableName,

        // Generic identifiers inside Source / FieldRef.
        Identifier: t.propertyName,

        // Arithmetic operators.
        // Lezer styleTags path syntax: bare strings may not contain '/', '!', or
        // lone '*' (wildcard); those node names must be double-quoted inside the key.
        // '+' and '-' are safe unquoted; '*' and '/' need quoting.
        '+': t.arithmeticOperator,
        '-': t.arithmeticOperator,
        '"*"': t.arithmeticOperator,
        '"/"': t.arithmeticOperator,

        // Comparison operators — '!=' and '>=' contain '!' and '=' sequences
        // that confuse the path parser unless the whole token is double-quoted.
        '=': t.compareOperator,
        '"!="': t.compareOperator,
        '<': t.compareOperator,
        '"<="': t.compareOperator,
        '>': t.compareOperator,
        '">="': t.compareOperator,

        // Structural punctuation.
        '(': t.paren,
        ')': t.paren,
        '[': t.bracket,
        ']': t.bracket,
        ',': t.separator,
        '.': t.separator,
        '@': t.operatorKeyword,
      }),
      indentNodeProp.add({
        // Keep Expression children aligned to the opening column.
        Expression: (context) => context.column(context.node.from),
      }),
    ],
  }),
  languageData: {
    // MetricQL has no comment syntax in v1; reserved for future extension.
    commentTokens: { line: '#' },
    closeBrackets: { brackets: ['(', '['] },
    // Re-indent on closing brackets.
    indentOnInput: /^\s*[)\]]$/,
  },
});

export function metricql(): LanguageSupport {
  return new LanguageSupport(metricqlLanguage);
}
