//go:build integration

package store_test

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/org/experimentation-platform/services/flags/internal/store"
)

type testEnv struct {
	store      *store.PostgresStore
	auditStore *store.PostgresAuditStore
	pool       *pgxpool.Pool
}

func setupIntegration(t *testing.T) testEnv {
	t.Helper()

	ctx := context.Background()
	pool, err := store.NewPool(ctx)
	require.NoError(t, err)
	t.Cleanup(pool.Close)

	// Clean test data from previous runs.
	_, err = pool.Exec(ctx, `DELETE FROM flag_audit_trail`)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, `DELETE FROM flag_variants`)
	require.NoError(t, err)
	_, err = pool.Exec(ctx, `DELETE FROM feature_flags`)
	require.NoError(t, err)

	return testEnv{
		store:      store.NewPostgresStore(pool),
		auditStore: store.NewPostgresAuditStore(pool),
		pool:       pool,
	}
}

func TestPostgresStore_CreateAndGetFlag(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	f := &store.Flag{
		Name:              "integration-test-flag",
		Description:       "A test flag",
		Type:              "BOOLEAN",
		DefaultValue:      "false",
		Enabled:           true,
		RolloutPercentage: 0.5,
	}

	created, err := env.store.CreateFlag(ctx, f)
	require.NoError(t, err)
	assert.NotEmpty(t, created.FlagID)
	assert.NotEmpty(t, created.Salt, "salt should be generated by database")
	assert.Equal(t, "integration-test-flag", created.Name)
	assert.Equal(t, 0.5, created.RolloutPercentage)
	assert.True(t, created.Enabled)

	// GetFlag.
	got, err := env.store.GetFlag(ctx, created.FlagID)
	require.NoError(t, err)
	assert.Equal(t, created.FlagID, got.FlagID)
	assert.Equal(t, created.Salt, got.Salt)
	assert.Equal(t, "A test flag", got.Description)
}

func TestPostgresStore_CreateFlagWithVariants(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	f := &store.Flag{
		Name:              "variant-test-flag",
		Type:              "STRING",
		DefaultValue:      "control",
		Enabled:           true,
		RolloutPercentage: 1.0,
		Variants: []store.FlagVariant{
			{Value: "control", TrafficFraction: 0.5},
			{Value: "treatment-a", TrafficFraction: 0.3},
			{Value: "treatment-b", TrafficFraction: 0.2},
		},
	}

	created, err := env.store.CreateFlag(ctx, f)
	require.NoError(t, err)
	require.Len(t, created.Variants, 3)
	assert.Equal(t, "control", created.Variants[0].Value)
	assert.Equal(t, 0.5, created.Variants[0].TrafficFraction)
	assert.Equal(t, 0, created.Variants[0].Ordinal)
	assert.Equal(t, "treatment-b", created.Variants[2].Value)
	assert.Equal(t, 2, created.Variants[2].Ordinal)

	// Variants have their own UUIDs.
	for _, v := range created.Variants {
		assert.NotEmpty(t, v.VariantID)
		assert.Equal(t, created.FlagID, v.FlagID)
	}
}

func TestPostgresStore_UpdateFlag(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	created, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "update-test-flag",
		Type:              "BOOLEAN",
		DefaultValue:      "false",
		RolloutPercentage: 0.1,
	})
	require.NoError(t, err)

	// Update rollout percentage.
	created.RolloutPercentage = 0.5
	created.Enabled = true
	updated, err := env.store.UpdateFlag(ctx, created)
	require.NoError(t, err)
	assert.Equal(t, 0.5, updated.RolloutPercentage)
	assert.True(t, updated.Enabled)
	assert.True(t, updated.UpdatedAt.After(created.UpdatedAt) || updated.UpdatedAt.Equal(created.UpdatedAt))
}

func TestPostgresStore_UpdateFlagVariants(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	created, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "update-variants-flag",
		Type:              "STRING",
		DefaultValue:      "default",
		RolloutPercentage: 1.0,
		Variants: []store.FlagVariant{
			{Value: "a", TrafficFraction: 0.5},
			{Value: "b", TrafficFraction: 0.5},
		},
	})
	require.NoError(t, err)
	require.Len(t, created.Variants, 2)

	// Replace variants with 3 new ones.
	created.Variants = []store.FlagVariant{
		{Value: "x", TrafficFraction: 0.3},
		{Value: "y", TrafficFraction: 0.3},
		{Value: "z", TrafficFraction: 0.4},
	}
	updated, err := env.store.UpdateFlag(ctx, created)
	require.NoError(t, err)
	require.Len(t, updated.Variants, 3)
	assert.Equal(t, "x", updated.Variants[0].Value)
	assert.Equal(t, "z", updated.Variants[2].Value)
}

func TestPostgresStore_DeleteFlag(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	created, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "delete-test-flag",
		Type:              "BOOLEAN",
		DefaultValue:      "false",
	})
	require.NoError(t, err)

	err = env.store.DeleteFlag(ctx, created.FlagID)
	require.NoError(t, err)

	_, err = env.store.GetFlag(ctx, created.FlagID)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "not found")
}

func TestPostgresStore_DeleteFlag_CascadesVariants(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	created, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "cascade-delete-flag",
		Type:              "STRING",
		DefaultValue:      "default",
		Variants: []store.FlagVariant{
			{Value: "a", TrafficFraction: 1.0},
		},
	})
	require.NoError(t, err)

	err = env.store.DeleteFlag(ctx, created.FlagID)
	require.NoError(t, err)

	// Variants should be cascaded.
	var count int
	err = env.pool.QueryRow(ctx,
		`SELECT COUNT(*) FROM flag_variants WHERE flag_id = $1`, created.FlagID).Scan(&count)
	require.NoError(t, err)
	assert.Equal(t, 0, count)
}

func TestPostgresStore_ListFlags(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	// Create 5 flags.
	for i := 0; i < 5; i++ {
		_, err := env.store.CreateFlag(ctx, &store.Flag{
			Name:              "list-flag-" + string(rune('a'+i)),
			Type:              "BOOLEAN",
			DefaultValue:      "false",
			RolloutPercentage: float64(i) * 0.2,
		})
		require.NoError(t, err)
	}

	// List all.
	flags, nextToken, err := env.store.ListFlags(ctx, 10, "")
	require.NoError(t, err)
	assert.Len(t, flags, 5)
	assert.Empty(t, nextToken, "should have no next page")

	// Paginated: page size 2.
	page1, token1, err := env.store.ListFlags(ctx, 2, "")
	require.NoError(t, err)
	assert.Len(t, page1, 2)
	assert.NotEmpty(t, token1)

	page2, token2, err := env.store.ListFlags(ctx, 2, token1)
	require.NoError(t, err)
	assert.Len(t, page2, 2)
	assert.NotEmpty(t, token2)

	page3, token3, err := env.store.ListFlags(ctx, 2, token2)
	require.NoError(t, err)
	assert.Len(t, page3, 1)
	assert.Empty(t, token3, "last page should have no next token")
}

func TestPostgresStore_GetAllEnabledFlags(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	// Create 3 flags: 2 enabled, 1 disabled.
	for i, enabled := range []bool{true, true, false} {
		_, err := env.store.CreateFlag(ctx, &store.Flag{
			Name:              "enabled-flag-" + string(rune('a'+i)),
			Type:              "BOOLEAN",
			DefaultValue:      "false",
			Enabled:           enabled,
			RolloutPercentage: 1.0,
		})
		require.NoError(t, err)
	}

	enabled, err := env.store.GetAllEnabledFlags(ctx)
	require.NoError(t, err)
	assert.Len(t, enabled, 2)
}

func TestPostgresStore_UniqueNameConstraint(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	_, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:         "unique-name-flag",
		Type:         "BOOLEAN",
		DefaultValue: "false",
	})
	require.NoError(t, err)

	_, err = env.store.CreateFlag(ctx, &store.Flag{
		Name:         "unique-name-flag",
		Type:         "BOOLEAN",
		DefaultValue: "false",
	})
	assert.Error(t, err, "duplicate name should fail")
}

func TestPostgresStore_SaltGenerated(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	f1, err := env.store.CreateFlag(ctx, &store.Flag{
		Name: "salt-test-1", Type: "BOOLEAN", DefaultValue: "false",
	})
	require.NoError(t, err)

	f2, err := env.store.CreateFlag(ctx, &store.Flag{
		Name: "salt-test-2", Type: "BOOLEAN", DefaultValue: "false",
	})
	require.NoError(t, err)

	assert.Len(t, f1.Salt, 32, "salt should be 16 bytes hex-encoded = 32 chars")
	assert.Len(t, f2.Salt, 32)
	assert.NotEqual(t, f1.Salt, f2.Salt, "each flag should have a unique salt")
}

// --- Audit Store Tests ---

func TestPostgresAuditStore_RecordAndGet(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	// Create a flag to audit.
	f, err := env.store.CreateFlag(ctx, &store.Flag{
		Name: "audit-test-flag", Type: "BOOLEAN", DefaultValue: "false",
	})
	require.NoError(t, err)

	// Record an audit entry.
	newVal, _ := json.Marshal(map[string]any{"enabled": true})
	err = env.auditStore.RecordAudit(ctx, &store.AuditEntry{
		FlagID:     f.FlagID,
		Action:     "enable",
		ActorEmail: "test@example.com",
		NewValue:   newVal,
	})
	require.NoError(t, err)

	// Retrieve.
	entries, err := env.auditStore.GetFlagAuditLog(ctx, f.FlagID, 10)
	require.NoError(t, err)
	require.Len(t, entries, 1)
	assert.Equal(t, "enable", entries[0].Action)
	assert.Equal(t, "test@example.com", entries[0].ActorEmail)
	assert.NotEmpty(t, entries[0].AuditID)
	assert.False(t, entries[0].CreatedAt.IsZero())
}

func TestPostgresAuditStore_GetStaleFlags(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	// Create a flag at 100% rollout.
	f, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "stale-test-flag",
		Type:              "BOOLEAN",
		DefaultValue:      "true",
		Enabled:           true,
		RolloutPercentage: 1.0,
	})
	require.NoError(t, err)

	// Backdate updated_at to 100 days ago.
	_, err = env.pool.Exec(ctx,
		`UPDATE feature_flags SET updated_at = NOW() - INTERVAL '100 days' WHERE flag_id = $1`,
		f.FlagID)
	require.NoError(t, err)

	// Query with 90-day threshold.
	stale, err := env.auditStore.GetStaleFlags(ctx, 90*24*time.Hour)
	require.NoError(t, err)
	require.Len(t, stale, 1)
	assert.Equal(t, f.FlagID, stale[0].FlagID)
	assert.Equal(t, "stale-test-flag", stale[0].Name)
	assert.True(t, stale[0].StaleDuration > 89*24*time.Hour)
}

func TestPostgresAuditStore_GetStaleFlags_NotStaleYet(t *testing.T) {
	env := setupIntegration(t)
	ctx := context.Background()

	// Create a fresh flag at 100%.
	_, err := env.store.CreateFlag(ctx, &store.Flag{
		Name:              "fresh-full-flag",
		Type:              "BOOLEAN",
		DefaultValue:      "true",
		Enabled:           true,
		RolloutPercentage: 1.0,
	})
	require.NoError(t, err)

	// Should not appear as stale (just created).
	stale, err := env.auditStore.GetStaleFlags(ctx, 90*24*time.Hour)
	require.NoError(t, err)
	assert.Empty(t, stale)
}
